version: '3.7'

services:

  backend:
    container_name: node_backend
    restart: always
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/quotes
    build: 
      context: ./api
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - postgres
    volumes:
      - ./api:/usr/src/app


  postgres:
    container_name: postgres
    image: postgres
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quotes
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports: 
      - '5432:5432'

  frontend:
    container_name: react_app
    build:
      context: ./react-app
      dockerfile: Dockerfile
    depends_on: 
      - backend
    volumes:
      - ./react-app:/usr/src/app
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

volumes:
  database-data: # named volumes can be managed easier using docker-compose
